"use server";

import React from "react";
import {
  Mail,
  Globe,
  Clock,
  Landmark,
  AlertTriangle,
  Shield,
  DollarSign,
} from "lucide-react";

const TermsOfService = () => {
  return (
    <main className="min-h-screen bg-gray-50 text-gray-800">
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        {/* Header */}
        <header className="text-center mb-12 border-b pb-4">
          <h1 className="text-3xl sm:text-4xl font-extrabold text-indigo-700 mb-2">
            Startinbox Terms of Service (ToS)
          </h1>

          <div className="text-sm text-gray-500 flex flex-col sm:flex-row items-center justify-center space-y-1 sm:space-y-0 sm:space-x-4">
            <span className="flex items-center">
              <Clock className="w-4 h-4 mr-2" />
              <strong>Effective Date:</strong> November 2025
            </span>

            <span className="flex items-center sm:hidden">|</span>

            <span className="flex items-center">
              <strong>Owner:</strong> Startinbox
            </span>
          </div>
        </header>

        {/* Introduction */}
        <section className="mb-8 p-6 bg-white rounded-lg shadow-md">
          <h2 className="text-2xl font-bold text-indigo-600 mb-3 flex items-center">
            <Landmark className="w-6 h-6 mr-2" /> 1. Introduction
          </h2>
          <p className="text-gray-700 leading-relaxed">
            Welcome to <strong>Startinbox</strong>, an AI-powered web platform
            that helps founders, students, and creators validate startup ideas,
            generate launch content, and connect with business growth tools.
          </p>
          <p className="mt-3 bg-yellow-50 p-3 border-l-4 border-yellow-500 rounded text-gray-700">
            By accessing or using Startinbox (the “Platform,” “Service,” or
            “Website”), you agree to be bound by these
            <strong className="font-semibold"> Terms of Service</strong>. Please
            read them carefully. If you do not agree, you may not use
            Startinbox.
          </p>
        </section>

        {/* Definitions */}
        <section className="mb-8 p-6 bg-white rounded-lg shadow-md">
          <h2 className="text-2xl font-bold text-indigo-600 mb-3">
            2. Definitions
          </h2>
          <ul className="list-disc list-inside space-y-2 text-gray-700">
            <li>
              <strong>“We”, “Us”, “Our”</strong>: Refer to Startinbox and its
              owner, Ngozi Annastasia Njoku.
            </li>
            <li>
              <strong>“User”, “You”, “Your”</strong>: Refer to any individual or
              entity using Startinbox.
            </li>
            <li>
              <strong>“Service”</strong>: Refers to the Startinbox platform,
              including the AI validation, content generation, and related
              add-ons.
            </li>
            <li>
              <strong>“AI Output”</strong>: Means the results, ideas, text, or
              recommendations generated by our AI engine.
            </li>
            <li>
              <strong>“Add-Ons”</strong>: Refer to optional services like
              consultation or product management support.
            </li>
          </ul>
        </section>

        {/* Eligibility */}
        <section className="mb-8 p-6 bg-white rounded-lg shadow-md">
          <h2 className="text-2xl font-bold text-indigo-600 mb-3">
            3. Eligibility
          </h2>
          <p className="text-gray-700 mb-3">To use Startinbox, you must:</p>
          <ul className="list-disc list-inside space-y-2 text-gray-700 ml-4">
            <li>
              Be at least <strong>18 years old</strong>.
            </li>
            <li>
              Have full <strong>legal capacity</strong> to enter into a binding
              agreement.
            </li>
            <li>
              Provide <strong>accurate and complete information</strong> during
              sign-up or purchase.
            </li>
            <li>
              If you use the Service on behalf of a company or team, you confirm
              that you have the <strong>authority</strong> to bind that entity
              to these Terms.
            </li>
          </ul>
        </section>

        {/* Description of Services*/}
        <section className="mb-8 p-6 bg-white rounded-lg shadow-md">
          <h2 className="text-2xl font-bold text-indigo-600 mb-3">
            4. Description of Services
          </h2>
          <ul className="list-disc list-inside space-y-3 text-gray-700 ml-4">
            <li>
              AI-Powered Idea Validation: Evaluates user-submitted business
              ideas and provides structured analysis.
            </li>
            <li>
              Launch Content Generation: Produces website copy, blog outlines,
              social media posts, and pitch decks.
            </li>
            <li>
              Influencer Outreach Copy: Generates suggested outreach messages
              for marketing.
            </li>
            <li>
              Add-On Services:
              <ul className="list-circle list-inside ml-6 mt-1">
                <li>
                  Consultation Call ($50) – One-hour strategy session via video
                  call.
                </li>
                <li>
                  Consultation Call ($100) – Two-hour strategy session via video
                  call.
                </li>
                <li>
                  Hire a Product Manager ($300/week) – Project management and
                  execution support.
                </li>
                <li>
                  Hire a Product Manager ($1000/month) – Project management and
                  execution support.
                </li>
              </ul>
            </li>
            <li>
              Educational Blog & Newsletter: Delivers startup insights and idea
              trends.
            </li>
            <li>
              User Reviews & Testimonials: Gathers feedback and displays user
              stories publicly.
            </li>
          </ul>
          <p className="mt-4 text-sm italic text-gray-500">
            <strong>Note:</strong> All AI results are generated using Google’s
            Generative AI (Gemini) and may include human-edited or curated
            content.
          </p>
        </section>

        {/* Payments and Refunds */}
        <section className="mb-8 p-6 bg-white rounded-lg shadow-md">
          <h2 className="text-2xl font-bold text-indigo-600 mb-3 flex items-center">
            <DollarSign className="w-6 h-6 mr-2" /> 5. Payments and Refunds
          </h2>
          <p className="text-gray-700 mb-3">
            Payments are securely processed through
            <strong className="font-semibold"> Paystack and Flutterwave</strong>
            . You agree to provide valid and complete payment information when
            purchasing any service.
          </p>
          <p className="text-gray-700 mb-3">
            We do not store or have access to your full card details. All prices
            are listed in <strong className="font-semibold">USD</strong> and may
            include applicable transaction fees.
          </p>

          <h3 className="text-xl font-semibold mt-4 mb-2">Current Pricing</h3>
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200 border">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Plan/Service
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Price (USD)
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                <tr>
                  <td className="px-6 py-4 whitespace-nowrap">Starter Plan</td>
                  <td className="px-6 py-4 whitespace-nowrap">$3.3</td>
                </tr>
                <tr>
                  <td className="px-6 py-4 whitespace-nowrap">Pro Plan</td>
                  <td className="px-6 py-4 whitespace-nowrap">$7.7</td>
                </tr>
                <tr>
                  <td className="px-6 py-4 whitespace-nowrap">Launch Bundle</td>
                  <td className="px-6 py-4 whitespace-nowrap">$16.5</td>
                </tr>
                <tr>
                  <td className="px-6 py-4 whitespace-nowrap">
                    Consultation Add-On
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    $50/1-hour-video-call
                  </td>
                </tr>
                <tr>
                  <td className="px-6 py-4 whitespace-nowrap">
                    Consultation Add-On
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    $100/2-hour-video-call
                  </td>
                </tr>
                <tr>
                  <td className="px-6 py-4 whitespace-nowrap">
                    Product Manager Add-On
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">$300/week</td>
                </tr>
                <tr>
                  <td className="px-6 py-4 whitespace-nowrap">
                    Product Manager Add-On
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">$1000/month</td>
                </tr>
              </tbody>
            </table>
          </div>

          <h3 className="text-xl font-semibold mt-6 mb-2">Refunds Policy</h3>
          <p className="text-gray-700">
            All payments are
            <strong className="font-semibold"> non-refundable</strong> once AI
            results or services have been delivered, except when:
          </p>
          <ul className="list-disc list-inside space-y-1 text-gray-700 ml-4">
            <li>A double charge occurs due to a technical error.</li>
            <li>
              The user was charged but did not receive any output within 48
              hours.
            </li>
          </ul>
          <p className="mt-3 text-sm text-gray-600">
            Refund requests must be submitted to{" "}
            <a
              href="mailto:support@startinbox.tech"
              className="text-indigo-600 hover:text-indigo-800 font-medium"
            >
              support@startinbox.tech
            </a>{" "}
            within <strong className="font-semibold">7 days</strong> of payment.
          </p>
        </section>

        {/* Intellectual Property */}
        <section className="mb-8 p-6 bg-white rounded-lg shadow-md">
          <h2 className="text-2xl font-bold text-indigo-600 mb-3">
            6. Intellectual Property
          </h2>
          <h3 className="text-xl font-semibold mb-2">
            A. Ownership of Platform
          </h3>
          <p className="text-gray-700 mb-4">
            All platform content, workflows, prompts, code, and branding belong
            exclusively to
            <strong className="font-semibold"> Startinbox</strong>. Unauthorized
            copying, redistribution, or modification is prohibited.
          </p>
          <h3 className="text-xl font-semibold mb-2">
            B. Ownership of AI Outputs
          </h3>
          <p className="text-gray-700">
            Users retain
            <strong className="font-semibold">
              ownership of the AI-generated outputs
            </strong>
            produced from their own ideas. However, Startinbox reserves the
            right to:
          </p>
          <ul className="list-disc list-inside space-y-1 text-gray-700 ml-4">
            <li>
              Use
              <strong className="font-semibold"> anonymized samples</strong> of
              non-identifiable outputs for product improvement or marketing
              (e.g., example reports).
            </li>
            <li>Remove outputs that violate these Terms or applicable laws.</li>
          </ul>
        </section>

        {/* Acceptable Use Policy */}
        <section className="mb-8 p-6 bg-red-50 rounded-lg shadow-md border-l-4 border-red-500">
          <h2 className="text-2xl font-bold text-red-700 mb-3 flex items-center">
            <AlertTriangle className="w-6 h-6 mr-2" /> 7. Acceptable Use Policy
          </h2>
          <p className="text-gray-700 mb-3">
            You agree <strong className="font-semibold">not</strong> to use
            Startinbox to:
          </p>
          <ul className="list-disc list-inside space-y-2 text-gray-700 ml-4">
            <li>
              Engage in
              <strong className="font-semibold">
                illegal, deceptive, or fraudulent
              </strong>
              activity.
            </li>
            <li>
              Upload, request, or generate
              <strong className="font-semibold">
                harmful, discriminatory, or offensive
              </strong>
              content.
            </li>
            <li>
              Copy or redistribute
              <strong className="font-semibold">
                proprietary AI prompts or data
              </strong>
              .
            </li>
            <li>
              Reverse-engineer, clone, or
              <strong className="font-semibold"> tamper</strong> with the
              system.
            </li>
          </ul>
          <p className="mt-3 text-sm text-red-600 font-medium">
            Violation of this section may result in
            <strong className="font-semibold">
              account suspension or legal action
            </strong>
            .
          </p>
        </section>

        {/* AI Limitations */}
        <section className="mb-8 p-6 bg-white rounded-lg shadow-md">
          <h2 className="text-2xl font-bold text-indigo-600 mb-3">
            8. AI Limitations
          </h2>
          <p className="text-gray-700 leading-relaxed">
            AI outputs are
            <strong className="font-semibold">
              informational and creative
            </strong>
            , not professional, financial, or legal advice.
          </p>
          <p className="mt-2 text-gray-700 leading-relaxed font-semibold">
            We make no guarantee that any AI-generated idea or recommendation
            will succeed in the real market. Users are fully responsible for
            their own business decisions.
          </p>
        </section>

        {/* Newsletter, Reviews, and Privacy */}
        <div className="grid md:grid-cols-2 gap-8 mb-8">
          <section className="p-6 bg-white rounded-lg shadow-md">
            <h2 className="text-xl font-bold text-indigo-600 mb-3">
              9. Newsletter & Marketing
            </h2>
            <p className="text-gray-700">
              By subscribing, you consent to receive startup-related content and
              product news. You may
              <strong className="font-semibold">
                {" "}
                unsubscribe at any time{" "}
              </strong>
              using the link in each email. We comply with GDPR and NDPR
              marketing consent standards.
            </p>
          </section>
          <section className="p-6 bg-white rounded-lg shadow-md">
            <h2 className="text-xl font-bold text-indigo-600 mb-3">
              10. User Reviews
            </h2>
            <p className="text-gray-700">
              By submitting a review, you grant Startinbox permission to display
              it for marketing. You may
              <strong className="font-semibold">
                request removal or edits
              </strong>
              by contacting support. We reserve the right to moderate reviews
              for clarity or compliance.
            </p>
          </section>
          <section className="p-6 bg-white rounded-lg shadow-md col-span-full">
            <h2 className="text-xl font-bold text-indigo-600 mb-3 flex items-center">
              <Shield className="w-5 h-5 mr-2" /> 11. Data Privacy
            </h2>
            <p className="text-gray-700">
              We process your personal data in accordance with our
              <strong className="font-semibold"> Privacy Policy</strong>, which
              you can review here:{" "}
              <a
                href="www.startinbox.tech/privacy-policy"
                className="text-indigo-600 hover:text-indigo-800 font-medium"
              >
                www.startinbox.tech/privacy-policy
              </a>
              .
            </p>
          </section>
        </div>

        {/* Liability, Termination, and Changes */}
        <section className="mb-8 p-6 bg-white rounded-lg shadow-md">
          <h2 className="text-2xl font-bold text-indigo-600 mb-3">
            12. Limitation of Liability
          </h2>
          <ul className="list-disc list-inside space-y-2 text-gray-700 ml-4">
            <li>
              Startinbox is
              <strong className="font-semibold"> not liable</strong> for any
              indirect, incidental, or consequential damages resulting from the
              use of our platform or services.
            </li>
            <li>
              Total liability for any claim shall
              <strong className="font-semibold">
                not exceed the amount paid
              </strong>
              by the user within the previous 30 days.
            </li>
            <li>
              We are not responsible for delays or disruptions caused by
              third-party providers (AI APIs, payment gateways, or communication
              tools).
            </li>
          </ul>

          <h2 className="text-2xl font-bold text-indigo-600 mt-6 mb-3">
            13. Account Termination
          </h2>
          <p className="text-gray-700 mb-2">
            We may suspend or terminate your access if you
            <strong className="font-semibold"> violate these Terms</strong>,
            engage in fraud, or abuse the platform.
          </p>
          <p className="text-gray-700 text-sm">
            Users may delete their account or request data removal by emailing{" "}
            <a
              href="mailto:contact@startinbox.tech"
              className="text-indigo-600 hover:text-indigo-800 font-medium"
            >
              contact@startinbox.tech
            </a>
            .
          </p>

          <h2 className="text-2xl font-bold text-indigo-600 mt-6 mb-3">
            14. Changes to Services or Terms
          </h2>
          <p className="text-gray-700">
            We may <strong className="font-semibold">update or modify </strong>
            these Terms periodically to reflect new features, tools, or legal
            requirements. If major changes occur, users will be notified by
            email or in-app message.
          </p>
        </section>

        {/* Governing Law and Contact */}
        <section className="p-6 bg-indigo-50 rounded-xl shadow-lg">
          <h2 className="text-2xl font-bold text-indigo-700 mb-3">
            15. Governing Law and Jurisdiction
          </h2>
          <p className="text-gray-700 mb-4">
            These Terms are governed by the laws of the
            <strong className="font-semibold">
              Federal Republic of Nigeria
            </strong>
            , with consideration for GDPR principles for international users.
            Any disputes shall be resolved amicably or through Nigerian courts.
          </p>

          <h2 className="text-2xl font-bold text-indigo-700 mb-3">
            16. Contact Information
          </h2>
          <p className="text-gray-700">
            If you have any questions about these Terms, please contact:
          </p>
          <ul className="list-none space-y-2 mt-2 font-medium">
            <li className="flex items-center">
              <Mail className="w-5 h-5 mr-2 text-indigo-600" />
              <strong className="font-semibold">Email: </strong>{" "}
              <a
                href="mailto:contact@startinbox.tech"
                className="text-indigo-600 hover:text-indigo-800"
              >
                contact@startinbox.tech
              </a>
            </li>
            <li className="flex items-center">
              <Globe className="w-5 h-5 mr-2 text-indigo-600" />
              <strong className="font-semibold">Website: </strong>{" "}
              <a
                href="www.startinbox.tech"
                className="text-indigo-600 hover:text-indigo-800"
              >
                www.startinbox.tech
              </a>
            </li>
          </ul>
        </section>
      </div>
    </main>
  );
};

export default TermsOfService;
