"""add-subscription-tables

Revision ID: 01bfcc3de7ca
Revises: 268b111b3b66
Create Date: 2025-08-31 22:22:31.806087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "01bfcc3de7ca"
down_revision: Union[str, Sequence[str], None] = "268b111b3b66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "si_subscription_plans",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_si_subscription_plans")),
        sa.UniqueConstraint("name", name=op.f("uq_si_subscription_plans_name")),
    )
    op.create_index(
        op.f("ix_si_subscription_plans_created_at"),
        "si_subscription_plans",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_si_subscription_plans_id"),
        "si_subscription_plans",
        ["id"],
        unique=True,
    )
    op.create_table(
        "si_subscription_plan_features",
        sa.Column("plan_id", sa.String(length=60), nullable=False),
        sa.Column("feature_name", sa.String(length=255), nullable=False),
        sa.Column(
            "value",
            sa.String(length=100),
            server_default="NULL",
            nullable=True,
            comment="optional limit",
        ),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["si_subscription_plans.id"],
            name=op.f("fk_si_subscription_plan_features_plan_id_si_subscription_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_si_subscription_plan_features")),
    )
    op.create_index(
        op.f("ix_si_subscription_plan_features_created_at"),
        "si_subscription_plan_features",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_si_subscription_plan_features_id"),
        "si_subscription_plan_features",
        ["id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_si_subscription_plan_features_plan_id"),
        "si_subscription_plan_features",
        ["plan_id"],
        unique=False,
    )
    op.add_column(
        "si_subscription_plans",
        sa.Column("is_default", sa.Boolean(), server_default="FALSE", nullable=False),
    )
    op.create_index(
        "uq_si_subscription_plans_is_default",
        "si_subscription_plans",
        ["is_default"],
        unique=False,
        postgresql_where=sa.text("is_default IS true"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        "uq_si_subscription_plans_is_default",
        table_name="si_subscription_plans",
        postgresql_where=sa.text("is_default IS true"),
    )
    op.drop_column("si_subscription_plans", "is_default")

    op.drop_index(
        op.f("ix_si_subscription_plan_features_plan_id"),
        table_name="si_subscription_plan_features",
    )
    op.drop_index(
        op.f("ix_si_subscription_plan_features_id"),
        table_name="si_subscription_plan_features",
    )
    op.drop_index(
        op.f("ix_si_subscription_plan_features_created_at"),
        table_name="si_subscription_plan_features",
    )
    op.drop_table("si_subscription_plan_features")
    op.drop_index(
        op.f("ix_si_subscription_plans_id"), table_name="si_subscription_plans"
    )
    op.drop_index(
        op.f("ix_si_subscription_plans_created_at"), table_name="si_subscription_plans"
    )
    op.drop_table("si_subscription_plans")
    # ### end Alembic commands ###
