"""add users.location column

Revision ID: 022e39a0850
Revises: 4e52c4a37d9
Create Date: 2025-09-15 23:35:35.567325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "022e39a0850"
down_revision: Union[str, Sequence[str], None] = "4e52c4a37d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "si_users", sa.Column("location", sa.String(length=100), nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("si_users", "location")
