"""remove feature usage table

Revision ID: 0be640553a1c
Revises: 6938d5908d0b
Create Date: 2025-09-10 22:01:27.888532

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0be640553a1c"
down_revision: Union[str, Sequence[str], None] = "6938d5908d0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        op.f("ix_si_user_feature_usage_created_at"), table_name="si_user_feature_usage"
    )
    op.drop_index(
        op.f("ix_si_user_feature_usage_id"), table_name="si_user_feature_usage"
    )
    op.drop_index(
        op.f("ix_si_user_feature_usage_user_subscription_id"),
        table_name="si_user_feature_usage",
    )
    op.drop_table("si_user_feature_usage")

    op.alter_column(
        "si_subscription_plans",
        "prompt",
        existing_type=sa.TEXT(),
        comment="The prompt for each plan.",
        existing_nullable=True,
    )
    op.drop_column("si_user_subscriptions", "start_date")
    op.drop_column("si_user_subscriptions", "auto_renew")
    op.drop_column("si_user_subscriptions", "next_payment_date")
    op.drop_column("si_user_subscriptions", "cancelled_at")
    op.drop_column("si_user_subscriptions", "end_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "si_user_subscriptions",
        sa.Column(
            "end_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
            comment="Only Free plans would have None",
        ),
    )
    op.add_column(
        "si_user_subscriptions",
        sa.Column(
            "cancelled_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "si_user_subscriptions",
        sa.Column(
            "next_payment_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "si_user_subscriptions",
        sa.Column(
            "auto_renew",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "si_user_subscriptions",
        sa.Column(
            "start_date",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text(
                "'2025-09-03 12:59:25.138192+01'::timestamp with time zone"
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "si_subscription_plans",
        "prompt",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="The prompt for each plan.",
        existing_nullable=True,
    )

    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "si_user_feature_usage",
        sa.Column(
            "user_subscription_id",
            sa.VARCHAR(length=60),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "feature_key", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "used_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.VARCHAR(length=60), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_subscription_id"],
            ["si_user_subscriptions.id"],
            name=op.f("fk_si_user_feature_usage_user_subscription_id_si_user_s_6ced"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_si_user_feature_usage")),
        sa.UniqueConstraint(
            "user_subscription_id",
            "feature_key",
            name=op.f("uq_feature_trackers_subscription_feature"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_si_user_feature_usage_user_subscription_id"),
        "si_user_feature_usage",
        ["user_subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_si_user_feature_usage_id"),
        "si_user_feature_usage",
        ["id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_si_user_feature_usage_created_at"),
        "si_user_feature_usage",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###
