"""add si_testimonials.idea_id

Revision ID: 0de4477cfccc
Revises: 37ded7ae7da6
Create Date: 2025-09-28 10:39:53.133694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0de4477cfccc'
down_revision: Union[str, Sequence[str], None] = '37ded7ae7da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('si_testimonials', sa.Column('idea_id', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('si_testimonials', 'idea_id')
    # ### end Alembic commands ###
