"""added addson table

Revision ID: 0ebdf3bacd11
Revises: a9f6bb36bd0f
Create Date: 2025-09-21 23:15:27.686320

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0ebdf3bacd11"
down_revision: Union[str, Sequence[str], None] = "a9f6bb36bd0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "si_adds_on_services",
        sa.Column(
            "name",
            sa.String(length=50),
            nullable=False,
            comment="Consult with a Startup Expert",
        ),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "details",
            sa.String(length=100),
            nullable=False,
            comment="e.g: /month, /2-hour-video-call",
        ),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_si_adds_on_services")),
    )
    op.create_index(
        op.f("ix_si_adds_on_services_created_at"),
        "si_adds_on_services",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_si_adds_on_services_id"), "si_adds_on_services", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_si_adds_on_services_name"),
        "si_adds_on_services",
        ["name"],
        unique=False,
    )
    op.alter_column(
        "si_payments",
        "subscription_plan_idx",
        existing_type=sa.INTEGER(),
        nullable=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f("ix_si_adds_on_services_name"), table_name="si_adds_on_services")
    op.drop_index(op.f("ix_si_adds_on_services_id"), table_name="si_adds_on_services")
    op.drop_index(
        op.f("ix_si_adds_on_services_created_at"), table_name="si_adds_on_services"
    )
    op.drop_table("si_adds_on_services")
    # ### end Alembic commands ###
