"""add adds_on_consultation table

Revision ID: 1882ab89d5cf
Revises: 0ebdf3bacd11
Create Date: 2025-09-22 12:55:22.381296

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1882ab89d5cf"
down_revision: Union[str, Sequence[str], None] = "0ebdf3bacd11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "si_adds_on_consultations",
        sa.Column("user_id", sa.String(length=60), nullable=True),
        sa.Column("startup_idea_id", sa.String(length=60), nullable=True),
        sa.Column("adds_on_one_id", sa.String(length=60), nullable=True),
        sa.Column(
            "is_adds_on_one_used", sa.Boolean(), server_default="FALSE", nullable=False
        ),
        sa.Column("adds_on_two_id", sa.String(length=60), nullable=True),
        sa.Column(
            "is_adds_on_two_used", sa.Boolean(), server_default="FALSE", nullable=False
        ),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["adds_on_one_id"],
            ["si_adds_on_services.id"],
            name=op.f("fk_si_adds_on_consultations_adds_on_one_id_si_adds_on_services"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["adds_on_two_id"],
            ["si_adds_on_services.id"],
            name=op.f("fk_si_adds_on_consultations_adds_on_two_id_si_adds_on_services"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["startup_idea_id"],
            ["si_startup_ideas.id"],
            name=op.f("fk_si_adds_on_consultations_startup_idea_id_si_startup_ideas"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["si_users.id"],
            name=op.f("fk_si_adds_on_consultations_user_id_si_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_si_adds_on_consultations")),
    )
    op.create_index(
        op.f("ix_si_adds_on_consultations_adds_on_one_id"),
        "si_adds_on_consultations",
        ["adds_on_one_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_si_adds_on_consultations_adds_on_two_id"),
        "si_adds_on_consultations",
        ["adds_on_two_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_si_adds_on_consultations_created_at"),
        "si_adds_on_consultations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_si_adds_on_consultations_id"),
        "si_adds_on_consultations",
        ["id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_si_adds_on_consultations_startup_idea_id"),
        "si_adds_on_consultations",
        ["startup_idea_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_si_adds_on_consultations_user_id"),
        "si_adds_on_consultations",
        ["user_id"],
        unique=False,
    )

    op.drop_constraint(
        op.f("fk_si_news_letter_subscriptions_user_id_si_users"),
        "si_news_letter_subscriptions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_si_news_letter_subscriptions_user_id_si_users"),
        "si_news_letter_subscriptions",
        "si_users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "si_payments",
        sa.Column("adds_on_consultation_id", sa.String(length=60), nullable=True),
    )
    op.create_index(
        op.f("ix_si_payments_adds_on_consultation_id"),
        "si_payments",
        ["adds_on_consultation_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_si_payments_adds_on_consultation_id_si_adds_on_consultations"),
        "si_payments",
        "si_adds_on_consultations",
        ["adds_on_consultation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        op.f("fk_si_social_oauths_user_id_si_users"),
        "si_social_oauths",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_si_social_oauths_user_id_si_users"),
        "si_social_oauths",
        "si_users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        op.f("fk_si_subscription_plan_features_plan_id_si_subscription_plans"),
        "si_subscription_plan_features",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_si_subscription_plan_features_plan_id_si_subscription_plans"),
        "si_subscription_plan_features",
        "si_subscription_plans",
        ["plan_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        op.f("fk_si_user_sessions_user_id_si_users"),
        "si_user_sessions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_si_user_sessions_user_id_si_users"),
        "si_user_sessions",
        "si_users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_si_user_sessions_user_id_si_users"),
        "si_user_sessions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_si_user_sessions_user_id_si_users"),
        "si_user_sessions",
        "si_users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_si_subscription_plan_features_plan_id_si_subscription_plans"),
        "si_subscription_plan_features",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_si_subscription_plan_features_plan_id_si_subscription_plans"),
        "si_subscription_plan_features",
        "si_subscription_plans",
        ["plan_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_si_social_oauths_user_id_si_users"),
        "si_social_oauths",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_si_social_oauths_user_id_si_users"),
        "si_social_oauths",
        "si_users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_si_payments_adds_on_consultation_id_si_adds_on_consultations"),
        "si_payments",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_si_payments_adds_on_consultation_id"), table_name="si_payments"
    )
    op.drop_column("si_payments", "adds_on_consultation_id")
    op.drop_constraint(
        op.f("fk_si_news_letter_subscriptions_user_id_si_users"),
        "si_news_letter_subscriptions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_si_news_letter_subscriptions_user_id_si_users"),
        "si_news_letter_subscriptions",
        "si_users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_si_adds_on_consultations_user_id"),
        table_name="si_adds_on_consultations",
    )
    op.drop_index(
        op.f("ix_si_adds_on_consultations_startup_idea_id"),
        table_name="si_adds_on_consultations",
    )
    op.drop_index(
        op.f("ix_si_adds_on_consultations_id"), table_name="si_adds_on_consultations"
    )
    op.drop_index(
        op.f("ix_si_adds_on_consultations_created_at"),
        table_name="si_adds_on_consultations",
    )
    op.drop_index(
        op.f("ix_si_adds_on_consultations_adds_on_two_id"),
        table_name="si_adds_on_consultations",
    )
    op.drop_index(
        op.f("ix_si_adds_on_consultations_adds_on_one_id"),
        table_name="si_adds_on_consultations",
    )
    op.drop_table("si_adds_on_consultations")
    # ### end Alembic commands ###
