"""added si_users.idempotency_key

Revision ID: 273fb823a3dd
Revises: d304122ff971
Create Date: 2025-09-01 12:15:28.172460

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "273fb823a3dd"
down_revision: Union[str, Sequence[str], None] = "d304122ff971"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "si_users", sa.Column("idempotency_key", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_si_users_idempotency_key"),
        "si_users",
        ["idempotency_key"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_si_users_idempotency_key"), table_name="si_users")
    op.drop_column("si_users", "idempotency_key")

    # ### end Alembic commands ###
