"""add si_user_sessions table

Revision ID: 2b40c0fb6bba
Revises: 273fb823a3dd
Create Date: 2025-09-01 16:53:04.269797

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2b40c0fb6bba"
down_revision: Union[str, Sequence[str], None] = "273fb823a3dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "si_user_sessions",
        sa.Column("user_id", sa.String(length=60), nullable=False),
        sa.Column("location", sa.String(length=150), nullable=True),
        sa.Column("ipaddress", sa.String(length=255), nullable=False),
        sa.Column("user_agent", sa.String(length=500), nullable=False),
        sa.Column("jti", sa.String(length=60), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["si_users.id"],
            name=op.f("fk_si_user_sessions_user_id_si_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_si_user_sessions")),
        sa.UniqueConstraint("jti", name=op.f("uq_si_user_sessions_jti")),
    )
    op.create_index(
        op.f("ix_si_user_sessions_created_at"),
        "si_user_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_si_user_sessions_id"), "si_user_sessions", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_si_user_sessions_user_id"),
        "si_user_sessions",
        ["user_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f("ix_si_user_sessions_user_id"), table_name="si_user_sessions")
    op.drop_index(op.f("ix_si_user_sessions_id"), table_name="si_user_sessions")
    op.drop_index(op.f("ix_si_user_sessions_created_at"), table_name="si_user_sessions")
    op.drop_table("si_user_sessions")
    # ### end Alembic commands ###
