"""updated testimonials table

Revision ID: 37ded7ae7da6
Revises: ab70852cf9cd
Create Date: 2025-09-26 23:31:58.349691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "37ded7ae7da6"
down_revision: Union[str, Sequence[str], None] = "ab70852cf9cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "si_testimonials", "testimonial", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "si_testimonials",
        "firstname",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )
    op.alter_column(
        "si_testimonials",
        "lastname",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )
    op.alter_column(
        "si_testimonials", "image_url", existing_type=sa.TEXT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "si_testimonials", "image_url", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "si_testimonials",
        "lastname",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )
    op.alter_column(
        "si_testimonials",
        "firstname",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )
    op.alter_column(
        "si_testimonials", "testimonial", existing_type=sa.TEXT(), nullable=False
    )
