"""Added blog_posts table

Revision ID: 3cfbc280306e
Revises: 42de394631be
Create Date: 2025-10-09 23:59:09.341479

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3cfbc280306e"
down_revision: Union[str, Sequence[str], None] = "42de394631be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "si_blog_posts",
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("image", sa.TEXT(), nullable=True),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_si_blog_posts")),
    )
    op.create_index(
        op.f("ix_si_blog_posts_created_at"),
        "si_blog_posts",
        ["created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_si_blog_posts_id"), "si_blog_posts", ["id"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f("ix_si_blog_posts_id"), table_name="si_blog_posts")
    op.drop_index(op.f("ix_si_blog_posts_created_at"), table_name="si_blog_posts")
    op.drop_table("si_blog_posts")
    # ### end Alembic commands ###
