"""add si_payments table

Revision ID: 41a9c9eed00e
Revises: d7df0be54512
Create Date: 2025-09-03 12:56:20.606825

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "41a9c9eed00e"
down_revision: Union[str, Sequence[str], None] = "d7df0be54512"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "si_user_subscriptions",
        sa.Column("user_id", sa.String(length=60), nullable=False),
        sa.Column("subscription_plan_id", sa.String(length=60), nullable=True),
        sa.Column(
            "start_date",
            sa.DateTime(timezone=True),
            server_default="NOW()",
            nullable=False,
        ),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("auto_renew", sa.Boolean(), server_default="TRUE", nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_payment_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_expired", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subscription_plan_id"],
            ["si_subscription_plans.id"],
            name=op.f(
                "fk_si_user_subscriptions_subscription_plan_id_si_subscription_plans"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["si_users.id"],
            name=op.f("fk_si_user_subscriptions_user_id_si_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_si_user_subscriptions")),
    )
    op.create_index(
        op.f("ix_si_user_subscriptions_created_at"),
        "si_user_subscriptions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_si_user_subscriptions_id"),
        "si_user_subscriptions",
        ["id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_si_user_subscriptions_subscription_plan_id"),
        "si_user_subscriptions",
        ["subscription_plan_id"],
        unique=False,
    )
    op.create_index(
        "uq_si_user_sub_composite_user_id_is_urrent",
        "si_user_subscriptions",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_current IS true"),
    )
    op.create_table(
        "si_payments",
        sa.Column("user_id", sa.String(length=60), nullable=True),
        sa.Column("subscription_plan_id", sa.String(length=60), nullable=True),
        sa.Column("user_subscription_id", sa.String(length=60), nullable=True),
        sa.Column(
            "provider",
            postgresql.ENUM(
                "stripe",
                "paystack",
                "flutterwave",
                "paypal",
                name="si_payment_provider_enum",
            ),
            nullable=False,
            comment="e.g., paystack/flutterwave/stripe/paypal",
        ),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "success",
                "failed",
                "refunded",
                "paid",
                "unpaid",
                "approved",
                "cancelled",
                "not_found",
                name="si_payment_status_enum",
            ),
            server_default="pending",
            nullable=False,
            comment="e.g., paid/unpaid/pending/approved/failed/cancelled",
        ),
        sa.Column(
            "tx_reference",
            sa.String(length=255),
            nullable=False,
            comment="the transaction refrence provided by the provider",
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subscription_plan_id"],
            ["si_subscription_plans.id"],
            name=op.f("fk_si_payments_subscription_plan_id_si_subscription_plans"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["si_users.id"],
            name=op.f("fk_si_payments_user_id_si_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_subscription_id"],
            ["si_user_subscriptions.id"],
            name=op.f("fk_si_payments_user_subscription_id_si_user_subscriptions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_si_payments")),
        sa.UniqueConstraint("tx_reference", name=op.f("uq_si_payments_tx_reference")),
    )
    op.create_index(
        op.f("ix_si_payments_created_at"), "si_payments", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_si_payments_id"), "si_payments", ["id"], unique=True)
    op.create_index(
        op.f("ix_si_payments_subscription_plan_id"),
        "si_payments",
        ["subscription_plan_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_si_payments_user_id"), "si_payments", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_si_payments_user_subscription_id"),
        "si_payments",
        ["user_subscription_id"],
        unique=False,
    )

    op.add_column(
        "si_subscription_plans",
        sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False),
    )
    op.add_column(
        "si_subscription_plans",
        sa.Column(
            "dummy",
            sa.Boolean(),
            server_default="TRUE",
            nullable=False,
            comment="used for enforcing is_default unique constraint. do not change to FALSE.",
        ),
    )
    op.drop_index(
        op.f("uq_si_subscription_plans_is_default"),
        table_name="si_subscription_plans",
        postgresql_where="(is_default IS TRUE)",
    )
    op.create_index(
        "uq_si_subscription_plans_is_default",
        "si_subscription_plans",
        ["dummy"],
        unique=True,
        postgresql_where="is_default is TRUE AND is_deleted IS FALSE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_si_subscription_plans_is_default",
        table_name="si_subscription_plans",
        postgresql_where="is_default is TRUE AND is_deleted IS FALSE",
    )
    op.create_index(
        op.f("uq_si_subscription_plans_is_default"),
        "si_subscription_plans",
        ["is_default"],
        unique=False,
        postgresql_where="(is_default IS TRUE)",
    )
    op.drop_column("si_subscription_plans", "dummy")
    op.drop_column("si_subscription_plans", "is_deleted")

    op.drop_index(op.f("ix_si_payments_user_subscription_id"), table_name="si_payments")
    op.drop_index(op.f("ix_si_payments_user_id"), table_name="si_payments")
    op.drop_index(op.f("ix_si_payments_subscription_plan_id"), table_name="si_payments")
    op.drop_index(op.f("ix_si_payments_id"), table_name="si_payments")
    op.drop_index(op.f("ix_si_payments_created_at"), table_name="si_payments")
    op.drop_table("si_payments")
    op.drop_index(
        "uq_si_user_sub_composite_user_id_is_urrent",
        table_name="si_user_subscriptions",
        postgresql_where=sa.text("is_current IS true"),
    )
    op.drop_index(
        op.f("ix_si_user_subscriptions_subscription_plan_id"),
        table_name="si_user_subscriptions",
    )
    op.drop_index(
        op.f("ix_si_user_subscriptions_id"), table_name="si_user_subscriptions"
    )
    op.drop_index(
        op.f("ix_si_user_subscriptions_created_at"), table_name="si_user_subscriptions"
    )
    op.drop_table("si_user_subscriptions")
    # ### end Alembic commands ###
