"""add users.agreed_to_terms

Revision ID: 42de394631be
Revises: ab48eea612c7
Create Date: 2025-10-03 13:23:31.071401

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "42de394631be"
down_revision: Union[str, Sequence[str], None] = "ab48eea612c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "si_users",
        sa.Column(
            "agreed_to_terms", sa.Boolean(), server_default="TRUE", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("si_users", "agreed_to_terms")
    # ### end Alembic commands ###
