"""added payments.payment_reference

Revision ID: 4e52c4a37d9
Revises: 0be640553a1c
Create Date: 2025-09-11 10:14:41.486000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4e52c4a37d9"
down_revision: Union[str, Sequence[str], None] = "0be640553a1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "si_payments",
        sa.Column(
            "payment_reference",
            sa.String(length=255),
            nullable=False,
            comment="the transaction reference provided by us.",
        ),
    )
    op.alter_column(
        "si_payments",
        "tx_reference",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
        comment="the transaction reference provided by the provider",
        existing_comment="the transaction refrence provided by the provider",
    )
    op.create_unique_constraint(
        op.f("uq_si_payments_payment_reference"), "si_payments", ["payment_reference"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_si_payments_payment_reference"), "si_payments", type_="unique"
    )
    op.alter_column(
        "si_payments",
        "tx_reference",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
        comment="the transaction refrence provided by the provider",
        existing_comment="the transaction reference provided by the provider",
    )
    op.drop_column("si_payments", "payment_reference")
