"""add si_social_oauth table

Revision ID: 51f0c7c55e71
Revises: 2b40c0fb6bba
Create Date: 2025-09-02 15:03:02.632659

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "51f0c7c55e71"
down_revision: Union[str, Sequence[str], None] = "2b40c0fb6bba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "si_social_oauths",
        sa.Column("user_id", sa.String(length=60), nullable=False),
        sa.Column("social_sub", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "email_verified", sa.Boolean(), server_default="FALSE", nullable=False
        ),
        sa.Column("family_name", sa.String(length=255), nullable=True),
        sa.Column("given_name", sa.String(length=255), nullable=False),
        sa.Column("picture", sa.TEXT(), nullable=True),
        sa.Column("access_token", sa.TEXT(), nullable=True),
        sa.Column("refresh_token", sa.TEXT(), nullable=True),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["si_users.id"],
            name=op.f("fk_si_social_oauths_user_id_si_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_si_social_oauths")),
        sa.UniqueConstraint(
            "email", "social_sub", name="uq_si_social_oauths_email_social_sub_composite"
        ),
    )
    op.create_index(
        op.f("ix_si_social_oauths_created_at"),
        "si_social_oauths",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_si_social_oauths_id"), "si_social_oauths", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_si_social_oauths_user_id"),
        "si_social_oauths",
        ["user_id"],
        unique=False,
    )

    op.add_column(
        "si_users",
        sa.Column(
            "sub",
            sa.String(length=255),
            nullable=True,
            comment="Socials user ID (sub claim from id_token)",
        ),
    )
    op.add_column(
        "si_users",
        sa.Column(
            "email_verified", sa.Boolean(), server_default="FALSE", nullable=False
        ),
    )
    op.create_unique_constraint(
        "uq_si_users_sub_signup_provider_composite",
        "si_users",
        ["signup_provider", "sub"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_si_users_sub_signup_provider_composite", "si_users", type_="unique"
    )
    op.drop_column("si_users", "email_verified")
    op.drop_column("si_users", "sub")

    op.drop_index(op.f("ix_si_social_oauths_user_id"), table_name="si_social_oauths")
    op.drop_index(op.f("ix_si_social_oauths_id"), table_name="si_social_oauths")
    op.drop_index(op.f("ix_si_social_oauths_created_at"), table_name="si_social_oauths")
    op.drop_table("si_social_oauths")
    # ### end Alembic commands ###
