"""updated adds-on prices to not null

Revision ID: 64cb1b8d6e1d
Revises: fac37e323e1d
Create Date: 2025-09-24 09:55:09.059397

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "64cb1b8d6e1d"
down_revision: Union[str, Sequence[str], None] = "fac37e323e1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "si_adds_on_services",
        "prices",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "si_adds_on_services",
        "prices",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )

    # ### end Alembic commands ###
