"""add newsletter.newsletter_hash

Revision ID: 6742401708e4
Revises: 8d8ca0a97783
Create Date: 2025-12-01 02:01:26.674653

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6742401708e4"
down_revision: Union[str, Sequence[str], None] = "8d8ca0a97783"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "si_news_letter_subscriptions",
        sa.Column("newsletter_hash", sa.String(length=60), nullable=True),
    )
    op.create_index(
        op.f("ix_si_news_letter_subscriptions_newsletter_hash"),
        "si_news_letter_subscriptions",
        ["newsletter_hash"],
        unique=True,
    )
    op.add_column(
        "si_news_letter_subscriptions",
        sa.Column("reason", sa.String(length=255), nullable=True),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_si_news_letter_subscriptions_newsletter_hash"),
        table_name="si_news_letter_subscriptions",
    )
    op.drop_column("si_news_letter_subscriptions", "newsletter_hash")
    op.drop_column("si_news_letter_subscriptions", "reason")

    # ### end Alembic commands ###
