""" remove sub.duration, added sub.idx

Revision ID: 6938d5908d0b
Revises: e40093d49e74
Create Date: 2025-09-09 15:30:55.559985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6938d5908d0b"
down_revision: Union[str, Sequence[str], None] = "e40093d49e74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "si_subscription_plans", sa.Column("idx", sa.Integer(), nullable=True)
    )
    op.create_unique_constraint(
        op.f("uq_si_subscription_plans_idx"), "si_subscription_plans", ["idx"]
    )
    op.drop_column("si_subscription_plans", "duration")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "si_subscription_plans",
        sa.Column("duration", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("uq_si_subscription_plans_idx"), "si_subscription_plans", type_="unique"
    )
    op.drop_column("si_subscription_plans", "idx")

