"""add news_letter table

Revision ID: 81f597890bd5
Revises: 51f0c7c55e71
Create Date: 2025-09-02 17:22:47.507167

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "81f597890bd5"
down_revision: Union[str, Sequence[str], None] = "51f0c7c55e71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "si_news_letter_subscriptions",
        sa.Column("user_id", sa.String(length=60), nullable=True),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "is_unsubscribed", sa.Boolean(), server_default="FALSE", nullable=False
        ),
        sa.Column("unsubscribed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["si_users.id"],
            name=op.f("fk_si_news_letter_subscriptions_user_id_si_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_si_news_letter_subscriptions")),
        sa.UniqueConstraint(
            "email", name=op.f("uq_si_news_letter_subscriptions_email")
        ),
    )
    op.create_index(
        op.f("ix_si_news_letter_subscriptions_created_at"),
        "si_news_letter_subscriptions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_si_news_letter_subscriptions_id"),
        "si_news_letter_subscriptions",
        ["id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_si_news_letter_subscriptions_user_id"),
        "si_news_letter_subscriptions",
        ["user_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        op.f("ix_si_news_letter_subscriptions_user_id"),
        table_name="si_news_letter_subscriptions",
    )
    op.drop_index(
        op.f("ix_si_news_letter_subscriptions_id"),
        table_name="si_news_letter_subscriptions",
    )
    op.drop_index(
        op.f("ix_si_news_letter_subscriptions_created_at"),
        table_name="si_news_letter_subscriptions",
    )
    op.drop_table("si_news_letter_subscriptions")
    # ### end Alembic commands ###
