"""add credits subscriptions

Revision ID: 8bb5ff955a82
Revises: 93aba4ebe61e
Create Date: 2026-02-16 07:14:24.281761

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8bb5ff955a82"
down_revision: Union[str, Sequence[str], None] = "93aba4ebe61e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_type t
                    JOIN pg_enum e ON t.oid = e.enumtypid
                    WHERE t.typname = 'si_subscription_type_enum'
                ) THEN
                    CREATE TYPE si_subscription_type_enum AS ENUM ('oneoff', 'reoccurring');
                END IF;
            END $$;
            """
        )
    )
    op.add_column(
        "si_payments",
        sa.Column("flutterwave_subscription_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "si_plan_usage_statistics",
        sa.Column(
            "silver_plan_stats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"use_count": 0}',
            nullable=False,
        ),
    )
    op.add_column(
        "si_plan_usage_statistics",
        sa.Column(
            "gold_plan_stats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"use_count": 0}',
            nullable=False,
        ),
    )
    op.add_column(
        "si_plan_usage_statistics",
        sa.Column(
            "diamond_plan_stats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"use_count": 0}',
            nullable=False,
        ),
    )
    op.add_column(
        "si_subscription_plans",
        sa.Column(
            "_type",
            postgresql.ENUM(
                "oneoff",
                "reoccurring",
                name="si_subscription_type_enum",
                create_type=False,
            ),
            server_default="oneoff",
            nullable=False,
        ),
    )
    op.add_column(
        "si_subscription_plans",
        sa.Column("credits", sa.BIGINT(), server_default="0", nullable=False),
    )
    op.add_column(
        "si_subscription_plans",
        sa.Column("flutterwave_plan_id", sa.BIGINT(), nullable=True),
    )
    op.create_unique_constraint(
        op.f("uq_si_subscription_plans_flutterwave_plan_id"),
        "si_subscription_plans",
        ["flutterwave_plan_id"],
    )
    op.add_column(
        "si_user_subscriptions",
        sa.Column("flutterwave_subscription_id", sa.BIGINT(), nullable=True),
    )
    op.add_column(
        "si_user_subscriptions",
        sa.Column("credit_used", sa.BIGINT(), server_default="0", nullable=False),
    )
    op.add_column(
        "si_user_subscriptions",
        sa.Column("remaining_credits", sa.BIGINT(), server_default="0", nullable=False),
    )
    op.add_column(
        "si_user_subscriptions",
        sa.Column(
            "_type",
            postgresql.ENUM("oneoff", "reoccurring", name="si_subscription_type_enum"),
            server_default="oneoff",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("si_user_subscriptions", "_type")
    op.drop_column("si_user_subscriptions", "remaining_credits")
    op.drop_column("si_user_subscriptions", "credit_used")
    op.drop_column("si_user_subscriptions", "flutterwave_subscription_id")
    op.drop_constraint(
        op.f("uq_si_subscription_plans_flutterwave_plan_id"),
        "si_subscription_plans",
        type_="unique",
    )
    op.drop_column("si_subscription_plans", "flutterwave_plan_id")
    op.drop_column("si_subscription_plans", "credits")
    op.drop_column("si_subscription_plans", "_type")
    op.drop_column("si_plan_usage_statistics", "diamond_plan_stats")
    op.drop_column("si_plan_usage_statistics", "gold_plan_stats")
    op.drop_column("si_plan_usage_statistics", "silver_plan_stats")
    op.drop_column("si_payments", "flutterwave_subscription_id")
    # ### end Alembic commands ###
