"""add plan-usage-statistic

Revision ID: 8d8ca0a97783
Revises: ad2300418cf7
Create Date: 2025-11-21 11:54:35.231803

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8d8ca0a97783"
down_revision: Union[str, Sequence[str], None] = "ad2300418cf7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "si_plan_usage_statistics",
        sa.Column("user_id", sa.String(length=60), nullable=False),
        sa.Column(
            "free_plan_stats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"use_count": 0}',
            nullable=False,
        ),
        sa.Column(
            "starter_plan_stats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"use_count": 0}',
            nullable=False,
        ),
        sa.Column(
            "pro_plan_stats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"use_count": 0}',
            nullable=False,
        ),
        sa.Column(
            "launch_bundle_plan_stats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"use_count": 0}',
            nullable=False,
        ),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["si_users.id"],
            name=op.f("fk_si_plan_usage_statistics_user_id_si_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_si_plan_usage_statistics")),
        sa.UniqueConstraint(
            "user_id", name=op.f("uq_si_plan_usage_statistics_user_id")
        ),
    )
    op.create_index(
        op.f("ix_si_plan_usage_statistics_created_at"),
        "si_plan_usage_statistics",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_si_plan_usage_statistics_id"),
        "si_plan_usage_statistics",
        ["id"],
        unique=True,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_si_plan_usage_statistics_id"), table_name="si_plan_usage_statistics"
    )
    op.drop_index(
        op.f("ix_si_plan_usage_statistics_created_at"),
        table_name="si_plan_usage_statistics",
    )
    op.drop_table("si_plan_usage_statistics")
    # ### end Alembic commands ###
