"""add blog.is_draft blog.owner_id

Revision ID: 93aba4ebe61e
Revises: cbd150e705d7
Create Date: 2026-01-10 16:42:11.785807

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "93aba4ebe61e"
down_revision: Union[str, Sequence[str], None] = "cbd150e705d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "si_blog_posts", sa.Column("owner_id", sa.String(length=60), nullable=True)
    )
    op.add_column(
        "si_blog_posts",
        sa.Column("is_draft", sa.Boolean(), server_default="FALSE", nullable=False),
    )
    op.create_index(
        op.f("ix_si_blog_posts_owner_id"), "si_blog_posts", ["owner_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_si_blog_posts_owner_id_si_users"),
        "si_blog_posts",
        "si_users",
        ["owner_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_si_blog_posts_owner_id_si_users"), "si_blog_posts", type_="foreignkey"
    )
    op.drop_index(op.f("ix_si_blog_posts_owner_id"), table_name="si_blog_posts")
    op.drop_column("si_blog_posts", "is_draft")
    op.drop_column("si_blog_posts", "owner_id")

    # ### end Alembic commands ###
