"""add subscription_plan_idx to payments table

Revision ID: a9f6bb36bd0f
Revises: 26f60eb7a798
Create Date: 2025-09-19 08:49:02.780860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a9f6bb36bd0f"
down_revision: Union[str, Sequence[str], None] = "26f60eb7a798"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "si_payments", sa.Column("subscription_plan_idx", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "si_subscription_plans",
        "idx",
        existing_type=sa.INTEGER(),
        # existing_nullable=True,
        nullable=False,
    )
    op.execute(
        sa.text(
            """
            UPDATE si_payments SET subscription_plan_idx = 1 WHERE si_payments.subscription_plan_id = 'starter';            
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE si_payments SET subscription_plan_idx = 2 WHERE si_payments.subscription_plan_id = 'pro';
            
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE si_payments SET subscription_plan_idx = 3 WHERE si_payments.subscription_plan_id = 'launch_bundle';
            
            """
        )
    )
    op.execute(
        sa.text(
            """
            ALTER TYPE si_payment_status_enum ADD VALUE 'no_payment_required';
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("si_payments", "subscription_plan_idx")
    # ### end Alembic commands ###
