"""added idea_next_step table

Revision ID: ab48eea612c7
Revises: 0de4477cfccc
Create Date: 2025-09-28 22:22:36.012231

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ab48eea612c7"
down_revision: Union[str, Sequence[str], None] = "0de4477cfccc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "si_idea_next_steps",
        sa.Column("user_id", sa.String(length=60), nullable=True),
        sa.Column("idea_id", sa.String(length=60), nullable=True),
        sa.Column("project_type", sa.String(length=255), nullable=False),
        sa.Column("project_stage", sa.String(length=255), nullable=False),
        sa.Column("desired_date", sa.Date(), nullable=False),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["idea_id"],
            ["si_startup_ideas.id"],
            name=op.f("fk_si_idea_next_steps_idea_id_si_startup_ideas"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["si_users.id"],
            name=op.f("fk_si_idea_next_steps_user_id_si_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_si_idea_next_steps")),
    )
    op.create_index(
        op.f("ix_si_idea_next_steps_created_at"),
        "si_idea_next_steps",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_si_idea_next_steps_id"), "si_idea_next_steps", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_si_idea_next_steps_idea_id"),
        "si_idea_next_steps",
        ["idea_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_si_idea_next_steps_user_id"),
        "si_idea_next_steps",
        ["user_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        op.f("ix_si_idea_next_steps_user_id"), table_name="si_idea_next_steps"
    )
    op.drop_index(
        op.f("ix_si_idea_next_steps_idea_id"), table_name="si_idea_next_steps"
    )
    op.drop_index(op.f("ix_si_idea_next_steps_id"), table_name="si_idea_next_steps")
    op.drop_index(
        op.f("ix_si_idea_next_steps_created_at"), table_name="si_idea_next_steps"
    )
    op.drop_table("si_idea_next_steps")
    # ### end Alembic commands ###
