"""added newsletter is sub sucess

Revision ID: ad2300418cf7
Revises: 9580c5ff77c6
Create Date: 2025-11-15 12:28:49.366618

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ad2300418cf7"
down_revision: Union[str, Sequence[str], None] = "9580c5ff77c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "si_news_letter_subscriptions",
        sa.Column(
            "is_sub_success", sa.Boolean(), server_default="FALSE", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("si_news_letter_subscriptions", "is_sub_success")
    # ### end Alembic commands ###
