"""add payments.purchase_event_id

Revision ID: cbd150e705d7
Revises: 6742401708e4
Create Date: 2025-12-05 08:43:11.123012

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cbd150e705d7"
down_revision: Union[str, Sequence[str], None] = "6742401708e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "si_payments",
        sa.Column("purchase_event_id", sa.String(length=60), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("si_payments", "purchase_event_id")

    # ### end Alembic commands ###
