"""add si_users table

Revision ID: d304122ff971
Revises: 01bfcc3de7ca
Create Date: 2025-09-01 09:26:32.925862

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d304122ff971"
down_revision: Union[str, Sequence[str], None] = "01bfcc3de7ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_type t
                    JOIN pg_enum e ON t.oid = e.enumtypid
                    WHERE t.typname = 'si_user_provider_enum'
                ) THEN
                    CREATE TYPE si_user_provider_enum AS ENUM ('google', 'apple', 'startinbox', 'github', 'facebook', 'twitter/x');
                END IF;
            END $$;
            """
        )
    )
    op.create_table(
        "si_users",
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("phone_number", sa.String(length=150), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("firstname", sa.String(length=150), nullable=True),
        sa.Column("lastname", sa.String(length=150), nullable=True),
        sa.Column("profile_photo", sa.TEXT(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="FALSE", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "signup_provider",
            postgresql.ENUM(
                "google",
                "apple",
                "startinbox",
                "github",
                "facebook",
                "twitter/x",
                name="si_user_provider_enum",
                create_type=False,
            ),
            server_default="startinbox",
            nullable=False,
        ),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_si_users")),
    )
    op.create_index(
        op.f("ix_si_users_created_at"), "si_users", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_si_users_email"), "si_users", ["email"], unique=True)
    op.create_index(op.f("ix_si_users_id"), "si_users", ["id"], unique=True)
    op.create_index(
        op.f("ix_si_users_phone_number"), "si_users", ["phone_number"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f("ix_si_users_phone_number"), table_name="si_users")
    op.drop_index(op.f("ix_si_users_id"), table_name="si_users")
    op.drop_index(op.f("ix_si_users_email"), table_name="si_users")
    op.drop_index(op.f("ix_si_users_created_at"), table_name="si_users")
    op.drop_table("si_users")
    # ### end Alembic commands ###
