"""add subscription.duration field

Revision ID: d7df0be54512
Revises: 81f597890bd5
Create Date: 2025-09-03 11:56:16.149419

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d7df0be54512"
down_revision: Union[str, Sequence[str], None] = "81f597890bd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "si_subscription_plans", sa.Column("duration", sa.Integer(), nullable=False)
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("si_subscription_plans", "duration")
    # ### end Alembic commands ###
