"""add testimonials table

Revision ID: db31eccbb36c
Revises: 1882ab89d5cf
Create Date: 2025-09-22 22:34:23.875105

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "db31eccbb36c"
down_revision: Union[str, Sequence[str], None] = "1882ab89d5cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "si_testimonials",
        sa.Column("testimonial", sa.TEXT(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("firstname", sa.String(length=100), nullable=False),
        sa.Column("lastname", sa.String(length=100), nullable=False),
        sa.Column("image_url", sa.TEXT(), nullable=False),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_si_testimonials")),
    )
    op.create_index(
        op.f("ix_si_testimonials_created_at"),
        "si_testimonials",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_si_testimonials_id"), "si_testimonials", ["id"], unique=True
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f("ix_si_testimonials_id"), table_name="si_testimonials")
    op.drop_index(op.f("ix_si_testimonials_created_at"), table_name="si_testimonials")
    op.drop_table("si_testimonials")
    # ### end Alembic commands ###
