"""add startup_ideas table

Revision ID: e40093d49e74
Revises: ebb5f7700e12
Create Date: 2025-09-08 19:11:46.038975

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e40093d49e74"
down_revision: Union[str, Sequence[str], None] = "ebb5f7700e12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "si_startup_ideas",
        sa.Column("user_id", sa.String(length=60), nullable=True),
        sa.Column("prompt", sa.TEXT(), nullable=False),
        sa.Column("idea_validation", sa.TEXT(), nullable=True),
        sa.Column("idea_score", sa.Integer(), nullable=True),
        sa.Column(
            "lean_canvas", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "ideal_customer_persona",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "suggested_startup_names",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "monetization_models",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "website_hero", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("blog_posts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "twitter_posts", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "elevator_pitch_slide",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "influencer_one", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "influencer_two", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "influencer_three", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("go_to_market_strategy_outline", sa.TEXT(), nullable=True),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["si_users.id"],
            name=op.f("fk_si_startup_ideas_user_id_si_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_si_startup_ideas")),
    )
    op.create_index(
        op.f("ix_si_startup_ideas_created_at"),
        "si_startup_ideas",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_si_startup_ideas_id"), "si_startup_ideas", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_si_startup_ideas_user_id"),
        "si_startup_ideas",
        ["user_id"],
        unique=False,
    )

    op.alter_column(
        "si_subscription_plan_features",
        "value",
        existing_type=sa.INTEGER(),
        comment="optional limit",
        existing_nullable=True,
    )
    op.add_column(
        "si_subscription_plans", sa.Column("prompt", sa.TEXT(), nullable=True)
    )
    op.alter_column(
        "si_user_subscriptions",
        "end_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        comment="Only Free plans would have None",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "si_user_subscriptions",
        "end_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        comment=None,
        existing_comment="Only Free plans would have None",
    )
    op.drop_column("si_subscription_plans", "prompt")
    op.alter_column(
        "si_subscription_plan_features",
        "value",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="optional limit",
        existing_nullable=True,
    )

    op.drop_index(op.f("ix_si_startup_ideas_user_id"), table_name="si_startup_ideas")
    op.drop_index(op.f("ix_si_startup_ideas_id"), table_name="si_startup_ideas")
    op.drop_index(op.f("ix_si_startup_ideas_created_at"), table_name="si_startup_ideas")
    op.drop_table("si_startup_ideas")
    # ### end Alembic commands ###
