"""add user.role, faqs table

Revision ID: ebb5f7700e12
Revises: eea1ea0f5f63
Create Date: 2025-09-06 00:29:55.525712

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ebb5f7700e12"
down_revision: Union[str, Sequence[str], None] = "eea1ea0f5f63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_type t
                    JOIN pg_enum e ON t.oid = e.enumtypid
                    WHERE t.typname = 'si_user_role_enum'
                ) THEN
                    CREATE TYPE si_user_role_enum AS ENUM ('admin', 'regular');
                END IF;
            END $$;
            """
        )
    )
    op.create_table(
        "si_faqs",
        sa.Column("question", sa.TEXT(), nullable=False),
        sa.Column("answer", sa.TEXT(), nullable=False),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_si_faqs")),
    )
    op.create_index(
        op.f("ix_si_faqs_created_at"), "si_faqs", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_si_faqs_id"), "si_faqs", ["id"], unique=True)
    op.drop_column("si_subscription_plan_features", "value")
    op.add_column(
        "si_subscription_plan_features",
        sa.Column(
            "value",
            sa.Integer(),
            nullable=True,
        ),
    )

    op.add_column(
        "si_subscription_plans",
        sa.Column("is_popular", sa.Boolean(), server_default="FALSE", nullable=False),
    )
    op.add_column(
        "si_users",
        sa.Column(
            "role",
            postgresql.ENUM("regular", "admin", name="si_user_role_enum"),
            server_default="regular",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("si_users", "role")
    op.drop_column("si_subscription_plans", "is_popular")
    op.drop_column("si_subscription_plan_features", "value")
    op.add_column(
        "si_subscription_plan_features",
        sa.Column(
            "value",
            sa.String(255),
            nullable=True,
        ),
    )

    op.drop_index(op.f("ix_si_faqs_id"), table_name="si_faqs")
    op.drop_index(op.f("ix_si_faqs_created_at"), table_name="si_faqs")
    op.drop_table("si_faqs")
    # ### end Alembic commands ###
