"""add user_feature_usage table

Revision ID: eea1ea0f5f63
Revises: 41a9c9eed00e
Create Date: 2025-09-03 23:22:48.375295

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "eea1ea0f5f63"
down_revision: Union[str, Sequence[str], None] = "41a9c9eed00e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "si_user_feature_usage",
        sa.Column("user_subscription_id", sa.String(length=60), nullable=False),
        sa.Column("feature_key", sa.String(length=100), nullable=False),
        sa.Column("used_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_subscription_id"],
            ["si_user_subscriptions.id"],
            name=op.f(
                "fk_si_user_feature_usage_user_subscription_id_si_user_subscriptions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_si_user_feature_usage")),
        sa.UniqueConstraint(
            "user_subscription_id",
            "feature_key",
            name="uq_feature_trackers_subscription_feature",
        ),
    )
    op.create_index(
        op.f("ix_si_user_feature_usage_created_at"),
        "si_user_feature_usage",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_si_user_feature_usage_id"),
        "si_user_feature_usage",
        ["id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_si_user_feature_usage_user_subscription_id"),
        "si_user_feature_usage",
        ["user_subscription_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        op.f("ix_si_user_feature_usage_user_subscription_id"),
        table_name="si_user_feature_usage",
    )
    op.drop_index(
        op.f("ix_si_user_feature_usage_id"), table_name="si_user_feature_usage"
    )
    op.drop_index(
        op.f("ix_si_user_feature_usage_created_at"), table_name="si_user_feature_usage"
    )
    op.drop_table("si_user_feature_usage")
    # ### end Alembic commands ###
