"""updated adds-on prices

Revision ID: fac37e323e1d
Revises: c79589f76b6d
Create Date: 2025-09-24 09:36:54.350218

"""

from typing import Sequence, Union
import json

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
revision: str = "fac37e323e1d"
down_revision: Union[str, Sequence[str], None] = "c79589f76b6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# adds on
add_ons = [
    {
        "id": "startup-consultant",
        "name": "Consult with a Startup Expert",
        "prices": [
            {"amount": 50, "unit": "/1-hour-video-call"},
            {"amount": 100, "unit": "/2-hours-video-call"},
        ],
    },
    {
        "id": "product-manager",
        "name": "Hire a Product Manager",
        "prices": [
            {"amount": 300, "unit": "week"},
            {"amount": 1000, "unit": "month"},
        ],
    },
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    op.add_column(
        "si_adds_on_consultations",
        sa.Column(
            "adds_on_one_price",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="e.g. {'amount': 200, 'unit': 'week'}",
        ),
    )
    op.add_column(
        "si_adds_on_consultations",
        sa.Column(
            "adds_on_two_price",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="e.g. {'amount': 50, 'unit': '1-hour video call'}",
        ),
    )
    op.add_column(
        "si_adds_on_services",
        sa.Column("prices", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.drop_column("si_adds_on_services", "details")
    op.drop_column("si_adds_on_services", "price")

    session.execute(sa.text("DELETE FROM si_adds_on_services"))
    session.commit()

    for add_on in add_ons:
        # Insert plan if not exists
        session.execute(
            sa.text(
                """
                INSERT INTO si_adds_on_services (id, name, prices)
                VALUES (:id, :name, :prices)
                ON CONFLICT (id) DO NOTHING
                """
            ),
            {
                "id": add_on["id"],
                "name": add_on["name"],
                "prices": json.dumps(add_on["prices"]),
            },
        )

    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute(sa.text("DELETE FROM si_adds_on_services"))
    session.commit()

    op.add_column(
        "si_adds_on_services",
        sa.Column(
            "price",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "si_adds_on_services",
        sa.Column(
            "details",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
            comment="e.g: /month, /2-hour-video-call",
        ),
    )
    op.drop_column("si_adds_on_services", "prices")
    op.drop_column("si_adds_on_consultations", "adds_on_two_price")
    op.drop_column("si_adds_on_consultations", "adds_on_one_price")

    # ### end Alembic commands ###
