"""
Init
"""

stripe_asesssion = {
    "adaptive_pricing": {"enabled": False},
    "after_expiration": None,
    "allow_promotion_codes": None,
    "amount_subtotal": 1500,
    "amount_total": 1500,
    "automatic_tax": {
        "enabled": False,
        "liability": None,
        "provider": None,
        "status": None,
    },
    "billing_address_collection": None,
    "branding_settings": {
        "background_color": "#ffffff",
        "border_style": "rounded",
        "button_color": "#0074d4",
        "display_name": "",
        "font_family": "default",
        "icon": None,
        "logo": None,
    },
    "cancel_url": "http://localhost:3000/checkout?canceled=true",
    "client_reference_id": "01996266ccef71c8a292e07bc1b9748e",
    "client_secret": None,
    "collected_information": {
        "business_name": None,
        "individual_name": None,
        "shipping_details": None,
    },
    "consent": None,
    "consent_collection": None,
    "created": 1758292531,
    "currency": "usd",
    "currency_conversion": None,
    "custom_fields": [],
    "custom_text": {
        "after_submit": None,
        "shipping_address": None,
        "submit": None,
        "terms_of_service_acceptance": None,
    },
    "customer": None,
    "customer_creation": "if_required",
    "customer_details": {
        "address": {
            "city": None,
            "country": "NG",
            "line1": None,
            "line2": None,
            "postal_code": None,
            "state": None,
        },
        "business_name": None,
        "email": "johnson29736@gmail.com",
        "individual_name": None,
        "name": "judason",
        "phone": None,
        "tax_exempt": "none",
        "tax_ids": [],
    },
    "customer_email": "johnson29736@gmail.com",
    "discounts": [],
    "expires_at": 1758294388,
    "id": "cs_test_a1WDjNllfDJnMcyjgQGmGYaEfKOq9EVPeFiR5AB2c44Hq9DkBaHSpPSICJ",
    "invoice": None,
    "invoice_creation": {
        "enabled": False,
        "invoice_data": {
            "account_tax_ids": None,
            "custom_fields": None,
            "description": None,
            "footer": None,
            "issuer": None,
            "metadata": {},
            "rendering_options": None,
        },
    },
    "livemode": False,
    "locale": None,
    "metadata": {
        "email": "johnson29736@gmail.com",
        "payment_ref": "01996266ccef71c8a292e07bc1b9748e",
        "sub_plan_id": "launch_bundle",
    },
    "mode": "payment",
    "object": "checkout.session",
    "origin_context": None,
    "payment_intent": "pi_3S95TMRokNMHHNlD1S7QA9BP",
    "payment_link": None,
    "payment_method_collection": "if_required",
    "payment_method_configuration_details": None,
    "payment_method_options": {"card": {"request_three_d_secure": "automatic"}},
    "payment_method_types": ["card"],
    "payment_status": "paid",
    "permissions": None,
    "phone_number_collection": {"enabled": False},
    "recovered_from": None,
    "saved_payment_method_options": None,
    "setup_intent": None,
    "shipping_address_collection": None,
    "shipping_cost": None,
    "shipping_options": [],
    "status": "complete",
    "submit_type": "pay",
    "subscription": None,
    "success_url": "http://localhost:3000/checkout?success=true",
    "total_details": {"amount_discount": 0, "amount_shipping": 0, "amount_tax": 0},
    "ui_mode": "hosted",
    "url": None,
    "wallet_options": None,
}

flutterwave_data = {
    "status": "success",
    "message": "Transaction fetched successfully",
    "data": {
        "id": 9656600,
        "tx_ref": "01995d0b24c872c0aa8b89da124abcc4",
        "flw_ref": "FLW-MOCK-1198137fbd4e05e4d7095a4f1307485d",
        "device_fingerprint": "N/A",
        "amount": 3,
        "currency": "USD",
        "charged_amount": 3,
        "app_fee": 0.12,
        "merchant_fee": 0,
        "processor_response": "Approved. Successful",
        "auth_model": "VBVSECURECODE",
        "ip": "54.75.161.64",
        "narration": "CARD Transaction ",
        "status": "successful",
        "payment_type": "card",
        "created_at": "2025-09-18T13:39:36.000Z",
        "account_id": 2584878,
        "card": {
            "first_6digits": "553188",
            "last_4digits": "2950",
            "issuer": " CREDIT",
            "country": "NIGERIA NG",
            "type": "MASTERCARD",
            "token": "flw-t1nf-7a7f4c539831222ad20b2b188e976367-m03k",
            "expiry": "09/32",
        },
        "meta": {
            "__CheckoutInitAddress": "https://checkout-v2.dev-flutterwave.com/v3/hosted/pay",
            "title": "Pay-as-you-go Service",
            "description": "One-time USD payment",
            "user_id": "01995a0f-a5ef-75c6-a8ec-8d4c5be59787",
            "sub_plan_id": "starter",
        },
        "amount_settled": 2.87,
        "customer": {
            "id": 3369102,
            "name": "Johnson Oragui Developer Freelance",
            "phone_number": "N/A",
            "email": "ravesb_c89bc522f3a3071fd295_33xsaint@gmail.com",
            "created_at": "2025-09-18T13:39:35.000Z",
        },
    },
}
